### ISSUE TITLE
AirPlay Receiver on macOS Occupies Port 5000

### ISSUE THREAD

**Issue by cathzzr2** [crown-of-napoleon/Florist-Database#10]
I just realized that the AirPlay Receiver on macOS is occupying port 5000, preventing me from running the program. Every time I attempted to stop the process using this port, the AirPlay Receiver seemed to automatically restart and cannot be killed manually. According to [macOS Port 5000 Mystery Solved from Reddit](https://www.reddit.com/r/perl/comments/10p8p39/macos_port_5000_mystery_solved/), disabling the AirPlay Receiver feature located in **System Settings -> AirDrop and Handoff** can release port 5000 and allow successful operation.

**Comment by crown-of-napoleon** [comment]
Fixed in the latest sync!
